name: build basic server and publish docker image
on: push

jobs:
  build:
     runs-on: ubuntu-latest
     steps: 

     - name: checkout
       uses: actions/checkout@v4.1.5

     - name: Login to Docker
       uses: docker/login-action@v3.1.0
       with:
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         
    - name:
         run: |
          docker build -t nodeserver:latest .
          docker tag nodeserver:latest benn1440/nodeserver:latest
          docker push benn1440/nodeserver:latest
